### ISSUE TITLE
Question about the certificates

### ISSUE THREAD

**Issue by stephenmoloney** [tiredofit/docker-jitsi-meet#14]
Hi I use `https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/` to generate letsencrypt certs
and I think it is probably leading the the error that I am seeing 

![image](https://user-images.githubusercontent.com/12668653/44213234-1facfe80-a165-11e8-827d-1da28dfa1eb3.png)

I'm thinking of using the letsencrypt cert instead - does that sound ok?

I'm not too familiar with jitsi to be honest.

**Comment by stephenmoloney** [comment]
I'm thinking something like a `CREATE_CERTS` option might help to make it optional

**Comment by tiredofit** [comment]
The Jitsi documentation is pretty lacking for tracing problems, agreed. We use the same reverse proxy and image for renewing certificates and haven't had a problem so far, although we are using an older revision of JVB, Meet, Jicofo going back to January or February. I'll ask one of my guys to put together a fresh copy on a development server to see if the image needs tweaking to support changes by upstream.

One thing with the LE certifcates is that they don't include the full chain in the cert.pem, so it is recommended to use fullchain.pem instead.  We use the LE certificates to deal with connecting to the jitsi-meet (web) component, and then use the self signed certificates that are generated via the prosody image to handle container to container communication. 

One of the Jitsi Meet developers has started work on a series of images for Jitsi Meet that I believe hopes to be "official" in the future. I am checking in on the progress every few weeks to see if I will learn something new about this rather complex stack.

**Comment by stephenmoloney** [comment]
```
We use the LE certificates to deal with connecting to the jitsi-meet (web) component, and then use the self signed certificates that are generated via the prosody image to handle container to container communication.
```

I tried that initially but I seem to keep getting this `You have been disconnected error`.

**Comment by stephenmoloney** [comment]
Ok, those official docker implementations seem to have landed...
https://jitsi.org/news/jitsi-meets-docker/
