### ISSUE TITLE
jitsi css

### ISSUE THREAD

**Issue by whiranpat** [tiredofit/docker-jitsi-meet#16]
I am having an issue where it can't get the all.css file. I am seeing it constantly reload the application:

`Uh oh! We couldn't fully download everything we needed :(
We will try again shortly. In the mean time, check for problems with your Internet connection!`

however if I do a curl on the server, I will see that it is running. Has anyone experience this before?

**Comment by sapkra** [comment]
You can try using the [official docker repository of jitsi meet](https://github.com/jitsi/docker-jitsi-meet).

It doesn't seem like this repository is getting maintained anymore.

**Comment by whiranpat** [comment]
thank you. I just trying to stay away from debian based image.
