### ISSUE TITLE
docker compose does not build

### ISSUE THREAD

**Issue by gurumark** [tiredofit/docker-jitsi-meet#3]
Hi,
I get the following error:

root@home:~/jitsi/docker-jitsi-meet/examples# docker-compose -p jitsi build
ERROR: build path /root/jitsi/docker-jitsi-meet/src/prosody either does not exist, is not accessible, or is not a valid URL.

**Comment by tiredofit** [comment]
Woops! You'll need to edit the docker-compose file and change the sections where it says `../src/` to just `../`

It looks like I uploaded my dev docker-compose.yml will change.
You can also pull the builds from Docker Hub as well.

**Comment by gurumark** [comment]
I have deleted the build instructions. Now I get:

root@home:~/jitsi# docker-compose up -d
Pulling prosody (prosody:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling prosody (prosody:latest)...
ERROR: pull access denied for prosody, repository does not exist or may require 'docker login'

**Comment by gurumark** [comment]
I get this when I changed the image names:

docker-compose up -d
Pulling prosody (tiredofit/prosody:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling prosody (tiredofit/prosody:latest)...
ERROR: pull access denied for tiredofit/prosody, repository does not exist or may require 'docker login'

**Comment by tiredofit** [comment]
As per the README.md
````
Installation

Automated builds of the image are available on Docker Hub and is the recommended method of installation.

docker pull tiredofit/jitsi-meet
docker pull tiredofit/jitsi-prosody
docker pull tiredofit/jitsi-videobridge
docker pull tiredofit/jitsi-jicofo
````

**Comment by gurumark** [comment]
Thanks. I tried that approach as well. It seems like it is pulling the images but can not pull them from docker-compose file. Am I missing something?:

~/jitsi# cat docker-compose.yml 
version: '2'

services:
  prosody:
    container_name: prosody
    image: tiredofit/prosody
    volumes:
      - ./logs/prosody:/var/log/prosody
      - ./certs:/certs

    environment:
      - HOST=meet.example.com

      - JITSI_VIDEO_PASS=secret1
      - JICOFO_PASS=secret2
      - JICOFO_USER_PASS=secret3
    networks:
      - proxy-tier
    restart: always

  jicofo:
    container_name: jicofo
    image: tiredofit/jicofo
    volumes:
      - ./logs/jicofo:/var/log/jitsi
      - ./certs:/certs

    environment:
      - PROSODY_HOST=prosody
      - HOST=meet.example.com

      - JICOFO_PASS=secret2
      - JICOFO_USER_PASS=secret3
    networks:
      - proxy-tier
    restart: always

  jvb:
    container_name: jvb
    image: tiredofit/jvb
    ports: 
      - 4443:4443
      - 10000-10100/udp
    volumes:
      - ./logs/jvb:/var/log/jitsi
      - ./certs:/certs

    environment:
      - HOST=meet.example.com
      - PROSODY_HOST=prosody
      - ENABLE_ZABBIX=FALSE
      - JITSI_VIDEO_PASS=secret1

      - NETWORK_MODE=NAT

    networks:
      - proxy-tier
    restart: always

  jitsi-meet:
    container_name: jitsi-meet
    image: tiredofit/jitsi-meet
    volumes:
      - ./assets/jitsi-meet:/assets/jitsi-meet
      - ./logs/nginx:/var/log/nginx
      - ./certs:/certs
    environment:
      - VIRTUAL_HOST=meet.example.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=meet.example.com
      - LETSENCRYPT_EMAIL=admin@example.com

      - JITSI_VIDEO_PASS=secret1
      - JICOFO_PASS=secret2
      - JICOFO_USER_PASS=secret3

      - PROSODY_HOST=prosody

    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: emdnet

**Comment by gurumark** [comment]
The image names were incorrect in my docker-compose.xml. After correcting those, it started up fine. Next up is opening up the ips from firewall.
